# Generated by Django 5.2 on 2025-04-07 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('Qualification', models.CharField(max_length=100)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeapp.department')),
                ('teach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
