# Generated by Django 5.2 on 2025-04-09 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
